[versions]
ktor = "1.6.7"
cache = "1.4.19-SNAPSHOT"

[libraries]
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
cache = { module = "com.runetopic.cache:cache", version.ref = "cache" }

[bundles]
ktor = ["ktor-server-netty"]
